name: CI Selenium Grid Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python3 -m venv venv
          ls -al  # Verificar si el entorno virtual se crea correctamente
          . ./venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install -r ./Valverde-Cano-Pruebas/requirements.txt

      - name: Start Selenium Grid
        run: |
          docker run -d -p 4444:4444 --name selenium-hub selenium/hub:4.5.0
          docker run -d --link selenium-hub:hub selenium/node-chrome:4.5.0
          docker run -d --link selenium-hub:hub selenium/node-firefox:4.5.0
          docker ps -a

      - name: Crear y guardar el Run ID en Testmo
        run: |
          ID=$(npx @testmo/testmo-cli automation:run:create \
            --instance "$TESTMO_URL" \
            --project-id 1 \
            --name "Selenium Grid Test Run" \
            --source "selenium-tests")  # Actualización aquí, el argumento --suite-id se ha removido
          echo "RUN_ID=$ID" >> $GITHUB_ENV  # Guardar el RUN_ID
        shell: bash
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}

      - name: Run Selenium tests on Grid
        working-directory: ./Valverde-Cano-Pruebas
        run: |
          . ../venv/bin/activate  # Asegúrate de que la ruta sea correcta
          python3 -m pytest --browser=chrome --alluredir=./allure-results
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub

      - name: Generate and upload Allure report
        working-directory: ./Valverde-Cano-Pruebas
        run: |
          allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./Valverde-Cano-Pruebas/allure-report

      - name: Subir resultados a Testmo
        run: |
          npx @testmo/testmo-cli automation:run:submit-thread \
            --instance "$TESTMO_URL" \
            --run-id "$RUN_ID" \
            --results allure-results/*.xml
        shell: bash
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
          RUN_ID: ${{ env.RUN_ID }}

      - name: Completar y marcar ejecución de prueba en Testmo
        run: |
          npx @testmo/testmo-cli automation:run:complete \
            --instance "$TESTMO_URL" \
            --run-id "$RUN_ID"
        shell: bash
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
          RUN_ID: ${{ env.RUN_ID }}

      - name: Clean up and stop Selenium Grid
        run: |
          docker stop selenium-hub
          docker rm selenium-hub
          docker stop $(docker ps -q --filter ancestor=selenium/node-chrome)
          docker stop $(docker ps -q --filter ancestor=selenium/node-firefox)
          docker rm $(docker ps -q --filter ancestor=selenium/node-chrome)
          docker rm $(docker ps -q --filter ancestor=selenium/node-firefox)
          rm -rf ./allure-results
          rm -rf ./allure-report
