name: Run Parallel Pytest with Selenium Grid, Allure Report, and Testmo Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-selenium pytest-allure-adaptor testmo

      - name: Run Pytest with Selenium Grid on ${{ matrix.browser }}
        run: |
          pytest --driver Remote --capability browserName=${{ matrix.browser }} --alluredir=./allure-results
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub

      - name: Generate Allure Report
        run: |
          allure generate ./allure-results --clean -o ./allure-report
          zip -r allure-report.zip ./allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report.zip

      - name: Upload Pytest logs
        run: zip -r pytest-logs.zip ./logs
        uses: actions/upload-artifact@v2
        with:
          name: pytest-logs
          path: pytest-logs.zip

      - name: Submit test results to Testmo
        run: |
          testmo submit results --test-files ./allure-results --project-id <YOUR_PROJECT_ID> --test-run-id <YOUR_RUN_ID>
        env:
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
