name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Python en la versi贸n necesaria
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Puedes ajustar esto a la versi贸n de Python que uses

      # 3. Instalar dependencias de Python y pytest
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest allure-pytest

      # 4. Crear la ejecuci贸n de pruebas en Testmo
      - name: Create and save the Testmo Run ID
        run: |
          ID=$(npx testmo automation:run:create \
          --instance "$TESTMO_URL" \
          --project-id 1 \
          --name "Selenium Grid Test Run" \
          --source "selenium-tests")
          echo "RUN_ID=$ID" >> $GITHUB_ENV  # Guardar el RUN_ID
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}

      # 5. Ejecutar las pruebas con pytest
      - name: Run Selenium tests with pytest
        run: |
          pytest --alluredir=./allure-results
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}

      # 6. Subir los resultados de pytest a Testmo
      - name: Submit Test Results to Testmo
        run: |
          npx testmo automation:run:submit-thread \
          --instance "$TESTMO_URL" \
          --run-id "$RUN_ID" \
          --results allure-results/*.xml
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
          RUN_ID: ${{ env.RUN_ID }}

      # 7. Completar la ejecuci贸n de la prueba en Testmo
      - name: Mark Test Run Complete in Testmo
        run: |
          npx testmo automation:run:complete \
          --instance "$TESTMO_URL" \
          --run-id "$RUN_ID"
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
          RUN_ID: ${{ env.RUN_ID }}

      # 8. Generar y subir el reporte de Allure
      - name: Generate and Upload Allure report
        run: |
          allure generate ./allure-results --clean -o ./allure-report
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}

      # 9. Subir el reporte de Allure como artefacto
      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report

