name: Parallel Pytest with Selenium Grid, Allure, and Testmo Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-selenium pytest-allure-adaptor

      - name: Download and Install Testmo CLI
        run: |
          curl -L https://get.testmo.com/cli/testmo-linux-amd64 -o testmo
          chmod +x testmo
          sudo mv testmo /usr/local/bin

  test-setup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Testmo Test Run
        run: |
          testmo run:create --name "Parallel Pytest Run" --project-id 1
        env:
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
          TESTMO_URL: ${{ secrets.TESTMO_URL }}

  test:
    runs-on: ubuntu-latest
    needs: test-setup
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-selenium pytest-allure-adaptor

      - name: Run Pytest with Selenium Grid on ${{ matrix.browser }}
        run: |
          pytest --driver Remote --capability browserName=${{ matrix.browser }} --alluredir=./allure-results
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub

      - name: Submit Test Results to Testmo
        run: |
          testmo run:submit-thread --run-id ${{ steps.test-setup.outputs.run-id }} --project-id 1
        env:
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
          TESTMO_URL: ${{ secrets.TESTMO_URL }}

      - name: Generate Allure Report
        run: |
          allure generate ./allure-results --clean -o ./allure-report
          zip -r allure-report.zip ./allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report.zip

  test-complete:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Mark Testmo Run as Complete
        run: |
          testmo run:complete --run-id ${{ steps.test-setup.outputs.run-id }} --project-id 1
        env:
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
          TESTMO_URL: ${{ secrets.TESTMO_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: test-complete
    steps:
      - name: Deploy Application
        run: echo "Deployment step here"
