name: Build, Test, and Generate Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Job para configurar el entorno y ejecutar las pruebas
  test-setup:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - uses: actions/checkout@v3

      # Crear el entorno virtual en el directorio correcto
      - name: Crear entorno virtual
        working-directory: ./Valverde-Cano-Pruebas  # Cambia al directorio correcto
        run: |
          python3 -m venv venv  # Crear el entorno virtual
          ls -la  # Verificar que el entorno virtual fue creado
          ls -la ./venv/bin  # Verificar si ./venv/bin existe
        shell: bash

      # Activar el entorno virtual, instalar dependencias y ejecutar pruebas
      - name: Activar entorno virtual y ejecutar pruebas
        working-directory: ./Valverde-Cano-Pruebas  # Cambia al directorio correcto
        run: |
          source ./venv/bin/activate  # Activar el entorno virtual
          python3 -m pip install --upgrade pip  # Actualizar pip
          pip install -r requirements.txt  # Instalar dependencias desde requirements.txt
          python3 -m pytest --browser=chrome --alluredir=./allure-results  # Ejecutar pytest y guardar los resultados
          npx @testmo/testmo-cli automation:run:submit-thread \
            --instance "$TESTMO_URL" \
            --run-id "25" \
            --results allure-results/*.xml  # Enviar resultados a Testmo
        shell: bash
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}

      # Subir logs y videos de pytest (si existen)
      - name: Upload pytest logs and videos
        uses: actions/upload-artifact@v3
        with:
          name: pytest-logs-and-videos
          path: ./Valverde-Cano-Pruebas/videos

      # Generar el reporte de Allure y subirlo como artefacto
      - name: Generate Allure Report
        working-directory: ./Valverde-Cano-Pruebas
        run: |
          allure generate ./allure-results --clean -o ./allure-report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./Valverde-Cano-Pruebas/allure-report
