name: CI Selenium Grid Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Set up virtual environment
        run: |
          python3 -m venv venv
          source ./venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Selenium Grid
        run: |
          docker run -d -p 4444:4444 --name selenium-hub selenium/hub:4.5.0  # Versión de Selenium Hub
          docker run -d --link selenium-hub:hub selenium/node-chrome:4.5.0  # Nodo de Chrome
          docker run -d --link selenium-hub:hub selenium/node-firefox:4.5.0  # Nodo de Firefox
          docker ps -a  # Verificación de contenedores Docker

      - name: Crear y guardar el Run ID en Testmo
        run: |
          ID=$(npx @testmo/testmo-cli automation:run:create \
            --instance "$TESTMO_URL" \
            --project-id 1 \  # Cambia el ID del proyecto si es necesario
            --name "Selenium Grid Test Run" \
            --suite-id 1 \  # Cambia el ID del suite si es necesario
            --source "selenium-tests")
          echo "RUN_ID=$ID" >> $GITHUB_ENV  # Guardar el RUN_ID en las variables de entorno
        shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}

      - name: Run Selenium tests on Grid
        run: |
          source ./venv/bin/activate
          python3 -m pytest --browser=chrome --alluredir=./allure-results  # Ejecutar pytest con Selenium Grid
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub  # URL del Selenium Grid Hub
        shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

      - name: Generar y subir reporte de Allure
        working-directory: ./Valverde-Cano-Pruebas
        run: |
          allure generate ./allure-results --clean -o ./allure-report
        - uses: actions/upload-artifact@v3
          with:
            name: allure-report
            path: ./allure-report

      - name: Subir resultados a Testmo
        run: |
          npx @testmo/testmo-cli automation:run:submit-thread \
            --instance "$TESTMO_URL" \
            --run-id "$RUN_ID" \
            --results allure-results/*.xml
        shell: /usr/bin/bash -e {0}
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
          RUN_ID: ${{ env.RUN_ID }}

      - name: Completar y marcar ejecución de prueba en Testmo
        run: |
          npx @testmo/testmo-cli automation:run:complete \
            --instance "$TESTMO_URL" \
            --run-id "$RUN_ID"
        shell: /usr/bin/bash -e {0}
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
          RUN_ID: ${{ env.RUN_ID }}

      - name: Clean up and stop Selenium Grid
        run: |
          docker stop selenium-hub
          docker rm selenium-hub
          docker stop $(docker ps -q --filter ancestor=selenium/node-chrome)
          docker stop $(docker ps -q --filter ancestor=selenium/node-firefox)
          docker rm $(docker ps -q --filter ancestor=selenium/node-chrome)
          docker rm $(docker ps -q --filter ancestor=selenium/node-firefox)
          rm -rf ./allure-results
          rm -rf ./allure-report
          deactivate
