name: Build, Test, Generate Allure Reports and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building the project .."

  test-setup:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      testmo-run-id: ${{ steps.run-tests.outputs.testmo-run-id }}
      
    steps:
      - uses: actions/checkout@v3

      # Instalar Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Cambiar a la carpeta correcta y levantar el grid de Selenium
      - name: Set up Selenium Grid with Docker Compose
        working-directory: ./Valverde-Cano-Pruebas
        run: |
          docker-compose up -d

      # Instalar Python y crear el entorno virtual
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Crear y activar el entorno virtual, luego guardar PATH
      - name: Activate virtualenv
        working-directory: ./Valverde-Cano-Pruebas
        run: |
          python3 -m venv venv  # Crear entorno virtual dentro de Valverde-Cano-Pruebas
          source venv/bin/activate  # Activar el entorno virtual
          echo "Activating virtualenv"
          python3 -m pip install --upgrade pip  # Actualizar pip
          pip install -r requirements.txt  # Instalar dependencias del requirements.txt
          pip install pytest  # Instalar pytest
          echo "PATH=$PATH" >> $GITHUB_ENV  # Guardar PATH en $GITHUB_ENV para que persista
        shell: bash

      # Instalar Node.js y Testmo CLI
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Testmo CLI
        run: |
          npm install -g @testmo/testmo-cli

      # Crear un test run en Testmo
      - run: |
          npx @testmo/testmo-cli automation:run:create \
            --instance "$TESTMO_URL" \
            --project-id 1 \
            --name "Parallel Selenium Test Run" \
            --source "selenium-tests" > testmo-run-id.txt
          ID=$(cat testmo-run-id.txt)
          echo "testmo-run-id=$ID" >> $GITHUB_OUTPUT
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
        id: run-tests

  test:
    needs: test-setup
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - uses: actions/checkout@v3

      # Ejecutar pruebas en paralelo para cada navegador
      - name: Run Selenium tests
        working-directory: ./Valverde-Cano-Pruebas
        run: |
          python3 -m pytest --browser=${{ matrix.browser }} --alluredir=./allure-results  # Ejecución directa del comando con el entorno activado
          npx @testmo/testmo-cli automation:run:submit-thread \
            --instance "$TESTMO_URL" \
            --run-id "${{ needs.test-setup.outputs.testmo-run-id }}" \
            --results allure-results/*.xml
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
        shell: bash

      # Subir logs de pytest y videos
      - name: Upload pytest logs and videos
        uses: actions/upload-artifact@v3
        with:
          name: pytest-logs-and-videos
          path: ./Valverde-Cano-Pruebas/videos

  test-complete:
    needs: [test-setup, test]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Marcar el test run como completo en Testmo
      - run: |
          npx @testmo/testmo-cli automation:run:complete \
            --instance "$TESTMO_URL" \
            --run-id "${{ needs.test-setup.outputs.testmo-run-id }}"
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}

      # Generar reporte de Allure y subirlo como artefacto
      - name: Generate Allure Report
        working-directory: ./Valverde-Cano-Pruebas
        run: |
          allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report

  deploy:
    needs: [test-complete]
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploying application .."
