name: CI Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Set up virtual environment
        run: |
          python3 -m venv venv
          source ./venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear y guardar el Run ID
        run: |
          RUN_ID=$(npx @testmo/testmo-cli automation:run:create \
            --instance "$TESTMO_URL" \
            --project-id 1 \  # Especifica el ID de tu proyecto
            --title "Selenium Test Run" \
            --description "Descripción de la ejecución de prueba" \
            --suite-id 1)  # Cambia el ID del suite si es necesario
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV  # Guardar el RUN_ID en las variables de entorno
        shell: /usr/bin/bash -e {0}
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}

      - name: Run Selenium tests
        run: |
          source ./venv/bin/activate
          python3 -m pytest --browser=chrome --alluredir=./allure-results  # Ejecutar pytest y guardar los resultados
        shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

      - name: Generar y subir reporte de Allure
        working-directory: ./Valverde-Cano-Pruebas
        run: |
          allure generate ./allure-results --clean -o ./allure-report
        - uses: actions/upload-artifact@v3
          with:
            name: allure-report
            path: ./allure-report

      - name: Subir resultados a Testmo
        run: |
          npx @testmo/testmo-cli automation:run:submit-thread \
            --instance "$TESTMO_URL" \
            --run-id "$RUN_ID" \
            --results allure-results/*.xml
        shell: /usr/bin/bash -e {0}
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
          RUN_ID: ${{ env.RUN_ID }}

      - name: Completar y marcar ejecución de prueba
        run: |
          npx @testmo/testmo-cli automation:run:complete \
            --instance "$TESTMO_URL" \
            --run-id "$RUN_ID"
        shell: /usr/bin/bash -e {0}
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
          RUN_ID: ${{ env.RUN_ID }}

      - name: Clean up
        run: |
          rm -rf ./allure-results
          rm -rf ./allure-report
          deactivate
