name: Selenium Test Grid CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-grid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker for Selenium Grid
        run: |
          docker network create selenium-grid
          docker pull greenvalve/selenium_testmo:selenium-hub
          docker run -d --network selenium-grid --name selenium-hub -p 4444:4444 greenvalve/selenium_testmo:selenium-hub

          # Descargar y ejecutar nodos para Chrome, Firefox, Edge
          docker pull greenvalve/selenium_testmo:video-node-chrome
          docker pull greenvalve/selenium_testmo:video-node-firefox
          docker pull greenvalve/selenium_testmo:video-node-edge

          docker run -d --network selenium-grid --name node-chrome -e HUB_HOST=selenium-hub greenvalve/selenium_testmo:video-node-chrome
          docker run -d --network selenium-grid --name node-firefox -e HUB_HOST=selenium-hub greenvalve/selenium_testmo:video-node-firefox
          docker run -d --network selenium-grid --name node-edge -e HUB_HOST=selenium-hub greenvalve/selenium_testmo:video-node-edge

      - name: Wait for Selenium Grid
        run: sleep 20  # Esperar que el Selenium Grid esté listo.

  run-tests:
    needs: setup-grid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Valverde-Cano-Pruebas/requirements.txt

      - name: Run Selenium tests on Grid
        run: |
          . venv/bin/activate  # Asegúrate de que esta línea esté correcta
          python3 -m pytest --browser=chrome --alluredir=./allure-results
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub

      - name: Generate and upload Allure report
        working-directory: ./Valverde-Cano-Pruebas
        run: |
          allure generate ./allure-results --clean -o ./allure-report
          docker run -v $PWD/allure-report:/app allure-docker-service-api upload --results /app
      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report
